### PR TITLE
allow async chunkGenerator + improve types

### PR DESCRIPTION
**Pull request by zardoy**
want to make optimizations by putting chunk generator into workers so it doesn't slow down main thread of flying squid

### CODE REVIEW

**Comment by extremeheat** [comment]
One thing to keep in mind that JavaScript will substantially slow if you pollute the event loop with lots of things, which can happen with use of async in hot places (as this results in creation of intermediate Promise's with callbacks). It creates lots of GC overhead, and creates processing delays for rest of code due to scheduling.

Using async also won't make the code faster/non-blocking, it will in fact block and slow the code even more because that code ultimately will have to run at some point on the current thread, and it'll happen over a longer period of time.

**Comment by extremeheat** [comment]
As we did in bedrock-protocol, you can greatly improve performance and throughput by removing async/Promise/timer use everywhere you can.

If you need to block for long periods of time, doing it in a worker thread and sending results back in form of an event that triggers another synchronous function inside main thread will minimize the overhead.

**Comment by zardoy** [comment]
> One thing to keep in mind that JavaScript will substantially slow if you pollute the event loop with lots of things, which can happen with use of async in hot places (as this results in creation of intermediate Promise's with callbacks). It creates lots of GC overhead, and creates processing delays for rest of code due to scheduling.

Yes but isn't it still better than synchronous code which will just block your event loop completely?

So just as you said I want to move chunk generator into worker and that's why I need this function to be async, I don't want to move prismarine-world into worker instead as by doing just the generator async we can also access already generated chunks while some other chunks are still in process. WDYT? Sorry I missed something

**Comment by extremeheat** [comment]
What I mean is I'd recommend moving away from async world completely if you are targeting performance.

> Yes but isn't it still better than synchronous code which will just block your event loop completely?

As mention, you block the event loop completely either way. And because of the overhead, you slow down and use more memory by doing async as opposed to blocking at once. In bedrock-protocol for example we've achieved 400 concurrent bots in one process by removing as much async operations as possible, because event loop yielding => congestion is pretty much the most expensive overhead you can get in JS.

**Pull request closed without merging**
