### PR TITLE
Added match while check intersect

### PR DESCRIPTION
**Pull request by sefirosweb**
Hi guys i'm interesed to check intersect at same time with other conditions,

Currently if i use match they no checks the intersect

```js
  if (block && (!matcher || matcher(block))) { // <<---
        const intersect = iter.intersect(block.shapes, position)
        if (intersect) {
          block.face = intersect.face
          block.intersect = intersect.pos
          return block
        }
      }
```

With this a small change can we use both,

** With this change I make a PR to block.js -> "canSeeBlock"
```js
function canSeeBlock (block, range = 5) {
    const headPos = bot.entity.position.offset(0, bot.entity.height, 0)
    const dir = block.position.offset(0.5, 0.5, 0.5).minus(headPos)
    const intersectMatch = inputBlock => block.position.equals(inputBlock.position) // <<--- also check position for avoid problems of water / air positions
    const blockAtCursor = bot.world.raycast(headPos, dir.normalize(), range, null, intersectMatch)
    return blockAtCursor && blockAtCursor.position.equals(block.position)
  }
```

### CODE REVIEW

**Comment by extremeheat** [comment]
I don't why there needs to be two functions, does the existing `match` function not work? It seems to have a higher precedence and it gets called right before the new matcher function.

**Comment by sefirosweb** [comment]
Hi @extremeheat,  i want to check " iter.intersect(block.shapes, position)" or "match" function,

But if match function exist the code skip iter.intersect

```js
 raycast (from, direction, range, matcher = null, intersectMatch = null) {
    const iter = new RaycastIterator(from, direction, range)
    let pos = iter.next()
    while (pos) {
      const position = new Vec3(pos.x, pos.y, pos.z)
      const block = this.getBlock(position)
      if (block && (!matcher || matcher(block))) { // <--- if match exist the check of intersect is skipped
        if (intersectMatch && intersectMatch(block)) { return block }
        const intersect = iter.intersect(block.shapes, position)
        if (intersect) {
          block.face = intersect.face
          block.intersect = intersect.pos
          return block
        }
      }
      pos = iter.next()
    }
    return null
  }
```

**Comment by extremeheat** [comment]
Ah ok, I see.

**Comment by sefirosweb** [comment]
Also I don't understand the "match" function,

Because if match() === false then -> check intersect 
else (true) => skip intersect 
if return "true" case they don't return the block, only skip intersect

Is this useful?  Maybe is used in project but i can't find it

**Comment by extremeheat** [comment]
I believe that `matcher` is supposed to filter out blocks you don't want, for example air, water, etc. 

The function you added basically skips the intersect test against the block shapes if your `intersectMatch` function returns a hit for the block.

In your `canSeeBlock` in blocks.js, it does a very narrow raycast to check blocks in a straight line, so it doesn't account for FOV or anything like that. It just checks if the the block is behind the cursor. If I'm following correctly, to get a wider match you want to test against the block coordinates and not test for an intersection? I don't think that's a good idea.

**Comment by sefirosweb** [comment]
Sorry for anoing,

I think matcher have an a bug, from documentations  say a different behavior

image

In this case the best option is fix this function, right?

**Comment by extremeheat** [comment]
Ah yes, looks like the docs are wrong compared to the code, they can be updated

**Comment by sefirosweb** [comment]
the question is is wrong documentation or code?

**Comment by sefirosweb** [comment]
For clarify, what is wrong the code or documentation?

**Comment by extremeheat** [comment]
cc @Karang

**Comment by sefirosweb** [comment]
The code can be solved with this:

```js
raycast(from, direction, range, matcher = null) {
    const iter = new RaycastIterator(from, direction, range)
    let pos = iter.next()
    while (pos) {
      const position = new Vec3(pos.x, pos.y, pos.z)
      const block = this.getBlock(position)
      if (block) {
        if (matcher) {
          if (matcher(block, iter)) {
            return block
          }
        } else {
          const intersect = iter.intersect(block.shapes, position)
          if (intersect) {
            block.face = intersect.face
            block.intersect = intersect.pos
            return block
          }
        }
      }
      pos = iter.next()
    }
    return null
  }
```
- If matcher exist -> then use this code
- If not exist use intersect 
- Also I added "intesrect" in matcher, for use a custom intersect behavior 

Only the question if matcher is used in any code of project

**Comment by extremeheat** [comment]
Can you explain in what situation you'd need to *not* check the bounding boxes for a match? I think this is the correct behavior. The player is looking at a block, but even if the player can *see* the block, the player is unable to break the block because the raycast fails as it should.

**Comment by sefirosweb** [comment]
I want to check if can see specifyc position (including air or water or something similar)

Currently is the specific position is air, the raycast no works propesly because is pointing until raycast end or intersect the air block to until solid block

Including a custom match we can add this behavior

**Review by Karang — APPROVED** [review]
LGTM, thanks

**Pull request merged**
