### PR TITLE
Add CubeIterator2d iterator

### PR DESCRIPTION
**Pull request by IceTank**
Generates spirals from a central position in growing squares.
Im not sure about the naming scheme if anyon has a better idea let me know.

### CODE REVIEW

**Comment by Karang** [comment]
This is what the Manhattan iterator does.

**Comment by IceTank** [comment]
Oh

**Comment by IceTank** [comment]
Ok but this implementation has less distance between its positions and is square shaped.

Sample from current Manhattan Iterator:
```
  |  |  |  |  |  |
  |  |  | 9|  |  |
  |  |10| 3| 8|  |
  |11| 4| 0| 2| 7|
  |  |12| 1| 6|  |
  |  |  | 5|  |  |
  |  |  |  |  |  |
```

This implementation:
```
  |  |  |  |  |  |
  |20|19|18|17|16|
  |21| 6| 5| 4|15|
  |22| 7| 0| 3|14|
  |23| 8| 1| 2|13|
  |24| 9|10|11|12|
  |  |  |  |  |  |
```

**Comment by Karang** [comment]
> Ok but this implementation has less distance between its positions and is square shaped.
> 
> Sample from current Manhattan Iterator:
> 
> ```
>   |  |  |  |  |  |
>   |  |  | 9|  |  |
>   |  |10| 3| 8|  |
>   |11| 4| 0| 2| 7|
>   |  |12| 1| 6|  |
>   |  |  | 5|  |  |
>   |  |  |  |  |  |
> ```
> 
> This implementation:
> 
> ```
>   |  |  |  |  |  |
>   |20|19|18|17|16|
>   |21| 6| 5| 4|15|
>   |22| 7| 0| 3|14|
>   |23| 8| 1| 2|13|
>   |24| 9|10|11|12|
>   |  |  |  |  |  |
> ```

Ah yes indeed it is slightly different. Spiral iterators have been used in the paste, but it would be nice indeed to have them here.
For reference:
* implementation in pviewer: https://github.com/PrismarineJS/prismarine-viewer/blob/master/viewer/lib/simpleUtils.js#L14
* spiralloop package https://www.npmjs.com/package/spiralloop (made for flying-squid)

**Comment by IceTank** [comment]
Is there anything still blocking this pull request?

**Comment by rom1504** [comment]
I think it would be ideal to add a simple test but otherwise lgtm

**Review by rom1504 — APPROVED** [review]

**Pull request merged**
