### PR TITLE
Push world to generator function

### PR DESCRIPTION
**Pull request by JWo1F**

### CODE REVIEW

**Comment by rom1504** [comment]
This is not correct and not enough.
a (world,chunkX,chunkZ) -> promise API might be interesting.
But the problem is it would mean 2 generation function can run "at the same time" which might be bad.
For example if the generation function is called at 3,4 and also put stuff at 3,3, and before its executed is over it is called at 3,3, then both function are going to try to put stuff at 3,3 which might result in unexpected results.
Should we trust the generator to have a lock mechanism ? should we try to handle that ourselves in prismarine-world ?
It does make things more complex anyway. Maybe there is a better way to do this.

**Comment by rom1504** [comment]
In order to solve this issue, a good way is to not actually generate the others chunks, but to cache the operations you need to do on them, and to do these operations only after these chunks are generated for other reasons. 

To keep a sane API, I think it might be better to provide only a way to write to the cache, and prismarine-world would handle actually writing to the chunk at the right time.

So the generating function would only do `cache.setBlockType(pos,type)` and not worry about where pos actually is.

**Comment by roblabla** [comment]
Note that the generation itself is still async (since it involves calls to the backend),  it's just the generator api that becomes sync and queuing commands

**Comment by rom1504** [comment]
Yeah, but that happens inside prisimarine-world, in getColumm , which is async anyway.

**Comment by rom1504** [comment]
@JWo1F is working on the cache

**Comment by JWo1F** [comment]
@rom1504 hey! I'm back and now I'm working on the cache. I don't understand, why world.js too hard. What methods is really async and what the one is fake-async? Why we have the initialize method? For what?

**Comment by rom1504** [comment]
Initialize is useful for https://github.com/rom1504/schematic-to-world but I can make the changes, if changes to the rest work ;)
Everything is async except the function that generate.

> And how can we start 2 generation function at the same time?

not sure what you mean, but ways to avoid deadlock are discussed above

**Comment by JWo1F** [comment]
@rom1504 see code, please. I have strange problem: "TypeError: Cannot read property 'Y' of undefined" (in tests).

**Comment by rom1504** [comment]
@JWo1F fixed, rebase ;)

**Comment by JWo1F** [comment]
@rom1504 rebased, all checks have passed :)

**Comment by rom1504** [comment]
Can you add something to the doc and provide an example on how to use this ?
Were you able to solve the initial problem using that code ? (Writing some more interesting generation, for example trees in between chunks)

**Comment by rom1504** [comment]
pretty old and outdated, let's close :)

**Pull request closed without merging**
